import type { Metadata } from "next";
import { Alice } from "next/font/google";
import "./globals.css";
import GlobalComponents from "@/components/GlobalComponents";

const inter = Alice({ weight: "400", subsets: ["cyrillic"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={
					inter.className + ` bg-gradient-to-b from-[#eea5a6] to-[#ffd0ec]`
				}
			>
				{children}
			</body>
		</html>
	);
}
